# Generated by Django 3.2.3 on 2021-05-17 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(db_table='likes_article', related_name='likes_art', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(db_table='likes_comment', related_name='likes_comm', to=settings.AUTH_USER_MODEL),
        ),
    ]
